### ISSUE TITLE
Definition of value semantics conflicts with MaybeUninit and unions

### ISSUE THREAD

**Issue by HeroicKatora** [ferrocene/specification#139]
> 7.9 It is undefined behavior to create a value from uninitialized memory. [For context] A value is either a literal or the result of a computation, that may be stored in a memory location, and interpreted based on some type.

However, this is incorrectly narrow. `MaybeUninit<u8>` is a type. The value `MaybeUninit<u8>::uninit()` contains uninitialized memory. We can copy that value without undefined behavior (or, `ptr::read` it). Both of these operations creates a new value from undefined memory but they shouldn't be defined as exhibiting UB; as they are and can be used in sound Rust programs.

Similarly, since `MaybeUninit` is no magic, other kinds of unions may also be created from unitialized memory.

The statement seems nevertheless important to define that in particular *Scalar Types* must not be created from uninitialized memory. But it may be necessary to split this statement as a case distinction by type category.

**Comment by Veykril** [comment]
> Similarly, since `MaybeUninit` is no magic, other kinds of unions may also be created from unitialized memory.

Do you have anything for me to verify this by any chance? I know that `MaybeUninit` is a lang item, so I am curios, I do think it shouldn't be magic in this regard but I'd rather double check if possible

**Comment by HeroicKatora** [comment]
This follows from [the reference on Union semantics](https://doc.rust-lang.org/stable/reference/items/unions.html#reading-and-writing-union-fields). Unions can be initialized from any field and the remaining is memory of the union's own layout is padding; which is left uninitialized. Conversely, 'rading a union field reads the bits of the union at the field's type.' and thus does not require bits other than that field to be initialized. Any union with a zero-sized-field can thus be valid even if it contains purely uninitialized memory.

    union Test {
        b: (),
        a: u32,
    }

For example this union has the layout of `u32` but is surely valid even if no bits are initialized. We can always read its `b` field.

The lang item `MaybeUninit` is magic in other regards, but validity invariants of its byte representation is not one of them.

**Comment by Veykril** [comment]
I see, thanks for clarifying :)
