### ISSUE TITLE
Integer arithmetic is not undefined (6.5.11)

### ISSUE THREAD

**Issue by HeroicKatora** [ferrocene/specification#143]
> 6.5.11:46 It is undefined behavior for an addition assignment, a division assignment, a multiplication assignment, a remainder assignment, or a subtraction assignment to cause overflow with values of numeric types.

> [For reference] Undefined Behavior 1.1.2:19 Situations that result in unbounded errors.

But the error behavior of integer overflows is quite bounded: panic (that is, potentially abort), or wrap. For division it is solely panic.
It would help understanding of anyone migrating from C specifications, to not call any aspects of (safe!) integer arithmetic 'undefined behavior'. Unspecified, maybe, or explicitly bounding the effect to unspecified value or panic.

**Comment by steveklabnik** [comment]
And as a citation, https://rust-lang.github.io/rfcs/0560-integer-overflow.html
