### ISSUE TITLE
Unsized coercion doesn't mention the CoerceUnsized trait

### ISSUE THREAD

**Issue by bjorn3** [ferrocene/specification#154]
This trait needs to be implemented for structs to allow unsizing in the first place.

**Comment by Veykril** [comment]
That is an unstable trait so it should not appear in the spec, the current stable rule for unsizing custom structs is specified in the spec (that is where the compiler implements said trait). We are mentioning `core::marker::Unsize` in the rules there which we shouldn't actually do though, I'll raise a new issue for that.
