### ISSUE TITLE
Glossary: "Undefined behavior" does not appear

### ISSUE THREAD

**Issue by ojeda** [ferrocene/specification#157]
UB is an important term that should most likely mentioned/defined in the glossary and probably referenced from other parts (e.g. unsafe related terms).

There is a mention in the "General" section which may be considered a definition (it is not in _italic_, though). But in that case, it is unclear what it exactly means, and it talks about "unbounded errors", which isn't defined or used anywhere else either.

**Comment by Veykril** [comment]
Added to the glossary in https://github.com/ferrocene/specification/pull/257
