### ISSUE TITLE
Clarify "all reachable control flow paths"

### ISSUE THREAD

**Issue by sanxiyn** [ferrocene/specification#167]
The phrase "all reachable control flow paths" is used for an uninitialized use error, but it is ambiguous. In fact, C# uses a possible different interpretation here.

There is no error in this C# code:

```c#
int x;
if (false) {
    Console.WriteLine(x);
}
```

But there is an error in this Rust code:

```rust
let x: i32;
if false {
    println!("{}", x);
}
```

**Comment by Veykril** [comment]
#433 changes phrasing slightly, we now have
> A :t:`variable` shall be used only after it has been initialized through all
:t:`[reachable control flow path]s` up to the point of its usage.

which is proper for the given rust snippet. `x` is used before being initialized in the control flow path between its usage and declaration.
