### ISSUE TITLE
CRLF is normalized to LF

### ISSUE THREAD

**Issue by bjorn3** [ferrocene/specification#172]
This means that even if you write a multi line string with CRLF, the program will only see LF. (This doesn't apply to `\r\n`, just the literal CR+LF character sequence)

**Comment by Veykril** [comment]
This is only observable in the program itself in multi-line strings I assume, right? (As in, if the rest of the program text has this normalization it won't affect the program's execution in any way)

**Comment by bjorn3** [comment]
It is also observable with proc macros I think. Other than that I don't think it affects execution.

**Comment by Veykril** [comment]
Hm, but proc macros don't see whitespace tokens so for them this also should only be observable with string literals as their input.

**Comment by bjorn3** [comment]
Multi line doc comments are visible to proc macros. For example if I have a proc macro `bar::print` which does `panic!("{ts:?}");` and a file like

```rust
fn main() {
    bar::print!(/**

*/);
    bar::print!(/**^M
^M
*/);
}
```

where ^M represents a carriage return, then compiling it will output

```
error: proc macro panicked
 --> src/main.rs:2:5
  |
2 | /     bar::print!(/**
3 | |
4 | | */);
  | |___^
  |
  = help: message: TokenStream [Punct { ch: '#', spacing: Alone, span: #0 bytes(28..35) }, Group { delimiter: Bracket, stream: TokenStream [Ident { ident: "doc", span: #0 bytes(28..35) }, Punct { ch: '=', spacing: Alone, span: #0 bytes(28..35) }, Literal { kind: Str, symbol: "\\n\\n", suffix: None, span: #0 bytes(28..35) }], span: #0 bytes(28..35) }]

error: proc macro panicked
 --> src/main.rs:5:5
  |
5 | /     bar::print!(/**
6 | |
7 | | */);
  | |___^
  |
  = help: message: TokenStream [Punct { ch: '#', spacing: Alone, span: #0 bytes(54..61) }, Group { delimiter: Bracket, stream: TokenStream [Ident { ident: "doc", span: #0 bytes(54..61) }, Punct { ch: '=', spacing: Alone, span: #0 bytes(54..61) }, Literal { kind: Str, symbol: "\\n\\n", suffix: None, span: #0 bytes(54..61) }], span: #0 bytes(54..61) }]
```

As you can see in both cases two line feeds and no carriage returns are in the doc comment.

**Comment by bjorn3** [comment]
Wait, you don't even need proc macros. This is enough:

```rust
macro_rules! print_comment {
    (#[doc = $doc:literal]) => { println!("{:?}", $doc); }
}

fn main() {
    print_comment!(/**

*/);
    print_comment!(/**^M
^M
*/);
}
```

```
     Running `target/debug/foo`
"\n\n"
"\n\n"
```

**Comment by Veykril** [comment]
Oh right, multi-line doc comment desugaring can also observe this 👍
