### ISSUE TITLE
Arithmetic overflow behavior should be tied to debug_assertions

### ISSUE THREAD

**Issue by steveklabnik** [ferrocene/specification#189]
From `871797b9f0c3cdd5dfe3e3d7c5b717ce20005532`:

> 6.5.5:42: If [arithmetic overflow](https://spec.ferrocene.dev/glossary.html#term_arithmetic_overflow) occurs, the computed [value](https://spec.ferrocene.dev/glossary.html#term_value) shall wrap around or the program shall either [panic](https://spec.ferrocene.dev/glossary.html#term_panic) or [abort](https://spec.ferrocene.dev/glossary.html#term_abort) execution.

This is *slightly incorrect*. While this sentence is true, [there's an additional restriction placed on implementations](https://rust-lang.github.io/rfcs/0560-integer-overflow.html 

> Implementations are permitted to check for overflow at any time (statically or dynamically). Implementations are required to at least check dynamically when debug_assert! assertions are enabled.

This second requirement is not properly captured in the text. @Veykril [mentioned](https://github.com/ferrocene/specification/pull/184#issuecomment-1201617228): 

> I haven't addressed it here because iirc we don't have a notion of debug assertions (yet) so I wasn't sure how to address that.

This is extremely reasonable! As far as I know, this is in fact the case: debug assertions is not in Ferrocene yet, and so defining semantics implied by their existence would be difficult.

Additionally, since the goal of Ferrocene is to describe rustc's behavior, rustc chooses the wrapping behavior when `debug_assertions` are not enabled. This may change in the future.

While I quoted the summary above, this section of the RFC has more formal language that may be useful when writing the Ferrocene specification: https://rust-lang.github.io/rfcs/0560-integer-overflow.html#arithmetic-operations-with-error-conditions

**Comment by Veykril** [comment]
So, `debug` builds / the concept of `debug_assertions` seems out of scope for the specification, which makes this situation a bit unfortunate for us. We are planning on qualfiying specifically 1.64 right now where wrapping behavior is the current behaviour, which that said we are planning on specifying this roughly like `Arithmetic overflow shall wrap the values around. An implementation is allowed to check for overflow and panic or abort respectively`

**Comment by steveklabnik** [comment]
> So, debug builds / the concept of debug_assertions seems out of scope for the specification

It's obviously up to you, but I'm a bit curious about this. The C and C++ standards have things like "an implementation is required to emit a diagnostic here," which feels kind of in the same ballpark. What's the objection about suggesting that implementations are required to have some sort of flag or switch?

**Comment by jonas-schievink** [comment]
The behavior here is tied to `-C overflow-checks`, not just `-C debug-assertions`. We now specify that two behaviors (wrapping and panicking) are allowed after https://github.com/ferrocene/specification/pull/330. I think compiler arguments will be documented elsewhere (I think in the tooling manual, not the language spec), so perhaps this can be closed?
