### ISSUE TITLE
Wrapping arithmetic overflow behavior should be defined as two's compliment wrapping

### ISSUE THREAD

**Issue by steveklabnik** [ferrocene/specification#190]
From `871797b9f0c3cdd5dfe3e3d7c5b717ce20005532`:

> 6.5.5:42: If [arithmetic overflow](https://spec.ferrocene.dev/glossary.html#term_arithmetic_overflow) occurs, the computed [value](https://spec.ferrocene.dev/glossary.html#term_value) shall wrap around or the program shall either [panic](https://spec.ferrocene.dev/glossary.html#term_panic) or [abort](https://spec.ferrocene.dev/glossary.html#term_abort) execution.

This is *slightly incorrect*. While this sentence is true, [it's not just wrapping](https://rust-lang.github.io/rfcs/0560-integer-overflow.html#arithmetic-operations-with-error-conditions), but specifically:

> When checking is disabled this will two's complement wrap.

Maybe this two's compliment requirement is covered elsewhere in the spec, but I figured I'd make sure to also file an issue, given that I noticed this while filing https://github.com/ferrocene/specification/issues/189.

**Comment by jonas-schievink** [comment]
We now specify

> 6.23:4 The resulting value may be truncated, discarding the most significant bits that do not fit in the target type.

which I think is correctly describing two's complement wrapping as well as unsigned integer wrapping?
