### ISSUE TITLE
Grammar ambiguity: Block expressions

### ISSUE THREAD

**Issue by e2-71828** [ferrocene/specification#355]
[&sect;6.4](https://spec.ferrocene.dev/expressions.html#block-expressions) defines a statement list as:
````
StatementList ::= Statement* Expression?
````

Clauses 3-8 then ascribe semantic meaning to whether or not an `Expression` is present, i.e. the block's return type and value.  There are, however, text strings that can be parsed as either a `Statement` or an `Expression`. If a block expression ends with one of these ambiguous text strings, the block's return type and value are also ambiguous according to the specification.

This particular problem appears when the final item in a block is an `ExpressionWithBlock`. It can be derived from either `Statement` or `Expression`:

````
Statement => ExpressionStatement => ExpressionWithBlock ;? => ExpressionWithBlock
Expression => ExpressionWithBlock
````

These two derivations lead to two different semantic interpretations:
1. The expression can be considered to be part of `Statement*` with no `Expression`, resulting in a unit type for the block as a whole. This appears to be the interpretation favored by the [Rust Reference](https://doc.rust-lang.org/reference/expressions/block-expr.html), but it does not match the compiler's actual behavior.
2. The expression can take the role of `Expression?`, resulting in its return value being used as the block's return value. This is the behavior exhibited by `rustc`.

cf. This [URLO Post](https://users.rust-lang.org/t/what-is-expr-what-is-stmt/82810/7?u=2e71828) by Tomek Czajka

**Comment by Veykril** [comment]
Good catch, indeed we should specify that this case parses as the tail expression.

**Comment by tczajka** [comment]
Besides `ExpressionWithBlock`, another ambiguity between `Statement` and `Expression` is:
```
Statement => TerminatedMacroInvocation => SimplePath ! { TokenTree* }
Expression => MacroInvocation => SimplePath ! DelimitedTokenTree => SimplePath ! { TokenTree* }
```
