### ISSUE TITLE
Fix use of "binding", "local variable", "object", "temporary", "variable"

### ISSUE THREAD

**Issue by pietroalbini** [ferrocene/specification#58]
*Issue exported from our legacy tracking system.*

**Comment by crlf0710** [comment]
Specially, the concept `object` is especially concerning, for example this code compiles today:
```rust
fn main() {
    let x: ();
}
```
There's a local variable that doesn't corresponds to a value at all. `Place`-related terms might explain the thing in a better way.

**Comment by kirtchev-adacore** [comment]
Thank you for the input!

Indeed, `object` is not a suitable term for Rust, and we will drop it.
Constants, statics, and variables (including bindings, local, local variables, and other similar aliases) will be defined in terms of values (or the lack there of).

**Comment by crlf0710** [comment]
Constants are defined in terms of values, statics are places always containing values. \<insert something about thread locals here.\> Variables are named places that sometimes has values if a value has been put into it, and the value hasn't been moved out of. 

Also note that in restricted cases it is also possible to move value out of the inner place provided by an outer value, e.g. moving a single field value out of a struct value, then the outer value becomes "incomplete" or "destructured". This is only possible when it doesn't have `Drop` implemented.

Something like this.
